__all__ = ['test',
           'adapter_info',
           'primer_info',
           'reference',
           'datasets',
           'miseq',
           'extract_subsample_reads',
           'mapping_utils',
           'filenames',
           'sequence_utils',
           'get_allele_counts',
           'minor_allele_frequency',
           'phix',
          ]
