__all__ = ['test',
           'adapter_info',
           'primer_info',
           'reference',
           'datasets',
           'miseq',
           'extract_subsample_reads',
           'mapping_utils',
           'filenames',
           'sequence_utils',
           'minor_allele_frequency',
          ]
