__all__ = ['adapter_info',
           'check_consensus',
           'check_overlaps',
           'coverage_tuples',
           'filenames',
           'filter_mapped_reads',
           'get_allele_counts',
           'minor_allele_frequency',
           'minor_allele_frequency_merged',
           'primer_info',
           'samples',
           'split_reads_for_mapping',
          ]
